navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    broadcast_cartesian_transform: 0.0429351  # For lat/long 55.944831, -3.186998
    yaw_offset: 0.0  # IMU reads 0 facing magnetic north, not east
    zero_altitude: false
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false

    imu0: /imu/data
    gps0: /gps/fix
    odometry_topic: /odometry/filtered